title: My personal blog - Hayden Moussa
email: Moussahj@hendrix.edu
description: > # this means to ignore newlines until "baseurl:"
  A blog to track my progess through college, focusing on my computer science career!
permalink: ':title/'
baseurl: "/csci340lab5" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Hayden Moussa # add your name
author-pic: Hayden-Face.jpg
about-author: My name is Hayden Moussa, I am a junior at hendrix college majoring in mathematics and computer science. 

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: HaydenMoussa # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: 'hay.j.m.13' # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: #mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
